title: Muhammad Faris Zuhairi
description: a Electrical Engineering Graduate specialized on Instrumentation, Control System, & Project Management.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
